# Generated by Django 5.1.5 on 2025-02-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="group_owner", to="auth.group"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="georeport.category",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        blank=True, related_name="owner", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("descrption", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "In Progess"),
                            (2, "Finished"),
                            (3, "Archive"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "_oldState",
                    models.IntegerField(
                        choices=[
                            (0, "New"),
                            (1, "In Progess"),
                            (2, "Finished"),
                            (3, "Archive"),
                        ],
                        default=0,
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reports",
                        to="georeport.category",
                    ),
                ),
            ],
        ),
    ]
