# Generated by Django 5.1.3 on 2024-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Finished')], default=0),
        ),
    ]
