# Generated by Django 5.1.5 on 2025-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
