# Generated by Django 5.1.5 on 2025-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeport', '0002_rename_descrption_report_description_report_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='close_with_link',
            field=models.BooleanField(default=False),
        ),
    ]
