# Generated by Django 5.1.4 on 2024-12-21 13:30

import django.db.models.deletion
import georeport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeport', '0002_report_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(default=georeport.models.get_default_related, on_delete=django.db.models.deletion.RESTRICT, to='georeport.category'),
        ),
    ]
