# Generated by Django 5.1.4 on 2025-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("georeport", "0003_category_alter_report_description_report_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="email",
            field=models.EmailField(default="mail@pinpoint.de", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
