# Generated by Django 5.1.5 on 2025-02-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeport', '0003_category_close_with_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
