# Copyright 2025 Jörn Menne
# Licensed under the Apache License, Version 2.0
# See NOTICE file for details.


# Major parts of this file were autogenerated by django

"""
Django settings for openpinpoint project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-loc#%lq_3s($un1$y#eh1%q(biw#0@ow6&7#ut$p0rufb*&dnl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".localhost", "127.0.0.1", "[::1]", "192.168.49.2"]


INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "geoentries",
    "mptt",
    "simple_history",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

# Corsheader config
if DEBUG:
    INSTALLED_APPS = [*INSTALLED_APPS, "corsheaders"]
    MIDDLEWARE = [*MIDDLEWARE, "corsheaders.middleware.CorsMiddleware"]
    CORS_ALLOWED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]

ROOT_URLCONF = "openpinpoint.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "openpinpoint.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


USE_POSTGRES = False
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if USE_POSTGRES:
    # DATABASES = {
    #    "default": {
    #        "ENGINE": "django.db.backends.postgresql",
    #        "OPTIONS": {
    #            "service": "geoentries",
    #        },
    #    }
    # }
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "pinpoint",
            "USER": "open",
            "PASSWORD": "pg123",
            # "HOST": "db",
            # "HOST": "localhost",
            "PORT": 5432,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST_FRAMEWORK Settings

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PARSER_CLASES": [
        "rest_framework_xml.parsers.XMLParser",
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_RENDER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework_xml.renderers.XMLRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

# E-Mail configuration. Emails will only be sent, if SEND_MAIL is set to request
SEND_MAIL = True
EMAIL_HOST = "localhost"
EMAIL_PORT = "8025"
DEFAULT_FROM_EMAIL = "example@pinpoint-report.de"  # Setup for ciphers

# WARNING: It is advised to use a fixed 32 byte string in production
# KEY = get_random_bytes(32)
KEY = b"0123456789abcdef0123456789abcdef"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Debug Toolbar settings
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

if not TESTING:
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        "debug_toolbar",
    ]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE,
    ]


# Minio as File-Storage
USE_MINIO = False
if USE_MINIO:
    MINIO_STORAGE_ENDPOINT = "localhost:9000"
    MINIO_STORAGE_ACCESS_KEY = "minio"
    MINIO_STORAGE_SECRET_KEY = "minio123"
    MINIO_STORAGE_USE_HTTPS = False
    MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
    MINIO_STORAGE_AUTO_CREATE_MEDIA_POLICY = "GET_ONLY"
    MINIO_STORAGE_MEDIA_BUCKET_NAME = "media"
    STORAGES = {
        "default": {
            "BACKEND": "minio_storage.storage.MinioMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

STATIC_URL = "static/"
STATIC_ROOT = "./static/"


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {message} {module}",
            # "datefmt": "%Y-%m-%d %H:%M:%S",
            "datefmt": "[%d/%b/%Y %H:%M:%S]",
            "style": "{",
        },
        "simple": {
            "format": "{asctime} {levelname} {message}",
            "datefmt": "[%d/%b/%Y %H:%M:%S]",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "ERROR",
    },
}
