# Generated by Django 6.0.2 on 2026-02-10 19:52

import django.core.validators
import django.db.models.deletion
import mptt.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("field_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[
                            ("exact", "Equals (==)"),
                            ("iexact", "Equals (Case-Insensitive)"),
                            ("contains", "Contains"),
                            ("gt", "Greater Than (>)"),
                            ("gte", "Greater Than or Equal (>=)"),
                            ("lt", "Less Than (<)"),
                            ("lte", "Less Than or Equal (<=)"),
                            ("in", "Is in (comma-separated list)"),
                        ],
                        default="exact",
                        max_length=32,
                    ),
                ),
                (
                    "expected_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "previous_value",
                    models.CharField(
                        blank=True,
                        help_text="Only needed for a transition change",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("trigger_on_create", models.BooleanField(default=True)),
                ("trigger_on_update", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("extern", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "monitoring_mail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="geoentries.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now=True)),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                ("done_date", models.DateField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (1, "In Progress"),
                            (2, "Closed"),
                            (3, "Archived"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("send_closelink", models.BooleanField(default=False)),
                (
                    "formated_adress",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entries",
                        to="geoentries.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categories", models.ManyToManyField(to="geoentries.category")),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("creation_time", models.DateTimeField(blank=True, editable=False)),
                ("update_time", models.DateTimeField(blank=True, editable=False)),
                ("done_date", models.DateField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (1, "In Progress"),
                            (2, "Closed"),
                            (3, "Archived"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("image", models.TextField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("send_closelink", models.BooleanField(default=False)),
                (
                    "formated_adress",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="geoentries.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical entry",
                "verbose_name_plural": "historical Entries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MailTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=128, unique=True)),
                ("model_name", models.CharField(max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("conditions", models.ManyToManyField(to="geoentries.condition")),
            ],
        ),
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("subject", models.CharField(max_length=80)),
                ("body", models.TextField(default="")),
                (
                    "mail_type",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("intern", "intern"),
                            ("extern", "extern"),
                        ],
                        default="info",
                        max_length=32,
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="mails",
                        to="geoentries.mailtrigger",
                    ),
                ),
            ],
        ),
    ]
