# Generated by Django 6.0.3 on 2026-03-17 08:30

import datetime
import django.core.validators
import django.db.models.deletion
import mptt.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fieldname"
                    ),
                ),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[
                            ("exact", "Equals (==)"),
                            ("iexact", "Equals (Case-Insensitive)"),
                            ("contains", "Contains"),
                            ("gt", "Greater Than (>)"),
                            ("gte", "Greater Than or Equal (>=)"),
                            ("lt", "Less Than (<)"),
                            ("lte", "Less Than or Equal (<=)"),
                            ("in", "Is in (comma-separated list)"),
                        ],
                        default="exact",
                        max_length=32,
                    ),
                ),
                (
                    "expected_value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Expected value",
                    ),
                ),
                (
                    "previous_value",
                    models.CharField(
                        blank=True,
                        help_text="Only needed for a transition change",
                        max_length=100,
                        null=True,
                        verbose_name="Previous value",
                    ),
                ),
                (
                    "trigger_on_create",
                    models.BooleanField(default=True, verbose_name="trigger on create"),
                ),
                (
                    "trigger_on_update",
                    models.BooleanField(default=True, verbose_name="trigger on update"),
                ),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "extern",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="External-Mail",
                    ),
                ),
                (
                    "monitoring_mail",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Monitoring-Mail",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(days=28), verbose_name="duration"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="geoentries.category",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation-time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Update-time"),
                ),
                (
                    "done_date",
                    models.DateField(blank=True, null=True, verbose_name="Done-date"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "open"),
                            (1, "in progress"),
                            (2, "closed"),
                            (3, "archived"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="Image"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Remark"),
                ),
                (
                    "send_closelink",
                    models.BooleanField(default=False, verbose_name="Send closelink"),
                ),
                (
                    "formated_adress",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Adress"
                    ),
                ),
                (
                    "show_image",
                    models.BooleanField(default=True, verbose_name="show_image"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entries",
                        to="geoentries.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="geoentries.category", verbose_name="Categories"
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupprofile",
                "verbose_name_plural": "Groupprofiles",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Creation-time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Update-time"
                    ),
                ),
                (
                    "done_date",
                    models.DateField(blank=True, null=True, verbose_name="Done-date"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "open"),
                            (1, "in progress"),
                            (2, "closed"),
                            (3, "archived"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "image",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Remark"),
                ),
                (
                    "send_closelink",
                    models.BooleanField(default=False, verbose_name="Send closelink"),
                ),
                (
                    "formated_adress",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Adress"
                    ),
                ),
                (
                    "show_image",
                    models.BooleanField(default=True, verbose_name="show_image"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="geoentries.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entry",
                "verbose_name_plural": "historical Entries",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Literal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "field",
                    models.CharField(max_length=100, null=True, verbose_name="field"),
                ),
                ("value", models.CharField(max_length=128, null=True)),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("iexact", "iexact"),
                            ("contains", "Contains"),
                            ("startswith", "startswith"),
                            ("istartswith", "istartswith"),
                            ("endwith", "endwith"),
                            ("iendwith", "iendwith"),
                            ("gt", "Greater than"),
                            ("gte", "greater than or equal"),
                            ("lt", "less than"),
                            ("lte", "less then or equal"),
                        ],
                        default="exact",
                        max_length=50,
                    ),
                ),
                ("is_negated", models.BooleanField(default=False)),
                ("is_previous_value", models.BooleanField(default=False)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"model__in": ["entry"]},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Literal",
                "verbose_name_plural": "Literals",
            },
        ),
        migrations.CreateModel(
            name="Disjunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("on_create", models.BooleanField(default=False)),
                ("on_update", models.BooleanField(default=True)),
                ("on_manual", models.BooleanField(default=False)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"model__in": ["entry"]},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "literals",
                    models.ManyToManyField(
                        blank=True, to="geoentries.literal", verbose_name="Literals"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=128, unique=True)),
                (
                    "model_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Modelname"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        to="geoentries.condition", verbose_name="Conditions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email-Trigger",
                "verbose_name_plural": "Email-Triggers",
            },
        ),
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, unique=True, verbose_name="Title"),
                ),
                ("subject", models.CharField(max_length=80, verbose_name="Subject")),
                ("body", models.TextField(default="", verbose_name="body")),
                (
                    "mail_type",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("intern", "intern"),
                            ("extern", "extern"),
                        ],
                        default="info",
                        max_length=32,
                        verbose_name="Mailtype",
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mails",
                        to="geoentries.mailtrigger",
                        verbose_name="template_triggers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email-Template",
                "verbose_name_plural": "EMail-Templates",
            },
        ),
    ]
