# Generated by Django 5.2.8 on 2026-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoentries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="extern",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
