# Generated by Django 6.0.1 on 2026-02-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoentries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="formated_adress",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="formated_adress",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
