# Generated by Django 5.2.8 on 2026-01-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoentries", "0002_category_extern"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="done_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="done_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
