# Generated by Django 5.2.8 on 2026-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoentries", "0003_entry_done_date_entry_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="send_closelink",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="send_closelink",
            field=models.BooleanField(default=False),
        ),
    ]
