# Generated by Django 6.0.1 on 2026-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geoentries", "0004_entry_send_closelink_historicalentry_send_closelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monitoring_mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
